# Jekyll configuration file for BillHertzing.github.io

title: Bill's Blog
description: >- # this means to ignore newlines until the next key, which is "baseurl:"
  Technical articles for my code repositories. Position papers on political issues. Cute pictures of the kids. I've got it all!
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://BillHertzing.github.io" 
twitter_username: whertzing56
github_username:  BillHertzing

# Build settings
markdown: kramdown
permalink: pretty
theme: minima
# https://html5up.net/minimaxing possibly?
# https://mmistakes.github.io/minimal-mistakes/ possibly?

plugins:
  - jekyll-feed
  - jekyll-timeago
  - jekyll_version_plugin
